# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6b6132cb3df22de2831c48a76d55bb94566870f561f833fad94667c4569ab60afe5220c03533f7892ef59cc90ecc03e0711ab02ef3798f1c8a0a8407bc1a34

test:
  secret_key_base: f7320b21db74400e88159b09d2fb6feb69b4210041d3b5e04af5c2ca84a710806ed1a28606d5339448eb7049478d55bc2a3d66549bdccbf959f6cfe659b1199a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
